/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.custom.lifeinsurance.quotations.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Quotation service. Represents a row in the &quot;Quotation_Quotation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.custom.lifeinsurance.quotations.model.impl.QuotationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.custom.lifeinsurance.quotations.model.impl.QuotationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Quotation
 * @generated
 */
@ProviderType
public interface QuotationModel
	extends BaseModel<Quotation>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a quotation model instance should use the {@link Quotation} interface instead.
	 */

	/**
	 * Returns the primary key of this quotation.
	 *
	 * @return the primary key of this quotation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this quotation.
	 *
	 * @param primaryKey the primary key of this quotation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this quotation.
	 *
	 * @return the uuid of this quotation
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this quotation.
	 *
	 * @param uuid the uuid of this quotation
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the quotation ID of this quotation.
	 *
	 * @return the quotation ID of this quotation
	 */
	public long getQuotationId();

	/**
	 * Sets the quotation ID of this quotation.
	 *
	 * @param quotationId the quotation ID of this quotation
	 */
	public void setQuotationId(long quotationId);

	/**
	 * Returns the group ID of this quotation.
	 *
	 * @return the group ID of this quotation
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this quotation.
	 *
	 * @param groupId the group ID of this quotation
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this quotation.
	 *
	 * @return the company ID of this quotation
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this quotation.
	 *
	 * @param companyId the company ID of this quotation
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this quotation.
	 *
	 * @return the user ID of this quotation
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this quotation.
	 *
	 * @param userId the user ID of this quotation
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this quotation.
	 *
	 * @return the user uuid of this quotation
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this quotation.
	 *
	 * @param userUuid the user uuid of this quotation
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this quotation.
	 *
	 * @return the user name of this quotation
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this quotation.
	 *
	 * @param userName the user name of this quotation
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this quotation.
	 *
	 * @return the create date of this quotation
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this quotation.
	 *
	 * @param createDate the create date of this quotation
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this quotation.
	 *
	 * @return the modified date of this quotation
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this quotation.
	 *
	 * @param modifiedDate the modified date of this quotation
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the customer ID of this quotation.
	 *
	 * @return the customer ID of this quotation
	 */
	public long getCustomerId();

	/**
	 * Sets the customer ID of this quotation.
	 *
	 * @param customerId the customer ID of this quotation
	 */
	public void setCustomerId(long customerId);

	/**
	 * Returns the quotation amount of this quotation.
	 *
	 * @return the quotation amount of this quotation
	 */
	public long getQuotationAmount();

	/**
	 * Sets the quotation amount of this quotation.
	 *
	 * @param quotationAmount the quotation amount of this quotation
	 */
	public void setQuotationAmount(long quotationAmount);

	/**
	 * Returns the quotation data of this quotation.
	 *
	 * @return the quotation data of this quotation
	 */
	@AutoEscape
	public String getQuotationData();

	/**
	 * Sets the quotation data of this quotation.
	 *
	 * @param quotationData the quotation data of this quotation
	 */
	public void setQuotationData(String quotationData);

	/**
	 * Returns the quotation type of this quotation.
	 *
	 * @return the quotation type of this quotation
	 */
	@AutoEscape
	public String getQuotationType();

	/**
	 * Sets the quotation type of this quotation.
	 *
	 * @param quotationType the quotation type of this quotation
	 */
	public void setQuotationType(String quotationType);

	@Override
	public Quotation cloneWithOriginalValues();

}